title: Aspire to Inspire
email: sreekanthreddybalne@gmail.com
tagline: >-
  Hola amigo
description: >-
  Stories about Python, AWS and Terraform
logo: /assets/media/logo.png
author: https://www.linkedin.com/in/sbalne/
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sreekanthreddybalne.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  sreekanthreddybalne
twitter:
  username: s_balne
  card: summary

social:
  name: Sreekanth Reddy Balne
  links:
    - https://twitter.com/s_balne
    - https://www.linkedin.com/in/sbalne
    - https://github.com/sreekanthreddybalne

# Build settings
# theme: minima
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  articles:
    output: true

feed:
  collections:
    - articles

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

whitelist:
  - jekyll-redirect-from
  - jekyll-feed

webrick:
  headers:
    Cache-Control: max-age=31536000
  